-- Aportar una card que NO esta en el catalogo.
--
-- POR QUE ESTA TABLA EXISTE PESE A LA DECISION D2
--
-- D2 dijo "una sola tabla card_images, NO crear card_submissions en el MVP", y
-- eso sigue valiendo para lo que era el MVP: aportar una imagen A UNA CARD QUE
-- YA EXISTE. Esto es otra cosa. `card_images.card_id` es NOT NULL con FK a
-- cards, asi que una propuesta de card nueva no tiene donde vivir ahi: la card
-- todavia no existe. Hacer card_id nullable seria peor -- romperia el indice
-- unico parcial (card_id, source_type), el lateral de cards_full y las policies
-- que se apoyan en el.
--
-- QUE SE PUEDE PROPONER Y QUE NO
--
-- Se propone una CARD dentro de un album que YA existe. No se proponen albums,
-- eras ni tipos: son 159 albums ya cargados, y abrir esa puerta multiplicaria
-- la superficie de moderacion, porque un album mal creado arrastra eras,
-- versiones y sets detras. Si el album falta de verdad, queda `notes` para
-- decirlo y que un mantenedor lo cree.
--
-- LA TAXONOMIA SE DERIVA, NO SE MANDA
--
-- El formulario cascadea tipo -> era -> album -> version -> categoria -> set
-- porque asi se elige sin ver 882 sets de golpe. Pero de todo eso solo
-- album_id, version_id, category_id y card_set_id son DATOS: el tipo y la era
-- se deducen del album. Guardar lo que mando el cliente permitiria una fila
-- incoherente -- una era de un tipo con un album de otro -- asi que un trigger
-- los rellena y ademas valida que la version y el set pertenezcan al album.

-- ---------------------------------------------------------------------------
-- 1. La tabla
-- ---------------------------------------------------------------------------

create table if not exists public.card_submissions (
  id bigint generated by default as identity primary key,

  -- Nullable y `on delete set null`, igual que card_images.contributed_by: si
  -- alguien borra su cuenta, la card que aporto sigue en el catalogo y el
  -- registro de la propuesta no se lleva por delante. El WITH CHECK de la
  -- policy de INSERT garantiza que al crearla nunca sea null.
  submitted_by uuid references auth.users(id) on delete set null,
  contributor_handle text,

  status public.image_status not null default 'pending',

  -- Lo que elige la persona.
  album_id integer not null references public.albums(id) on delete cascade,
  version_id integer references public.album_versions(id) on delete set null,
  category_id integer not null references public.card_categories(id),
  card_set_id bigint references public.card_sets(id) on delete set null,

  -- Derivado del album por trigger. Se guarda para que la bandeja de moderacion
  -- pueda agrupar y filtrar sin rehacer la cadena de joins.
  era_id bigint references public.album_eras(id) on delete set null,
  collection_type_id bigint references public.collection_types(id) on delete set null,

  member text not null,
  card_name text not null,
  notes text,

  -- La imagen es obligatoria: aportar una card sin foto no resuelve nada, el
  -- hueco seguiria ahi.
  bucket_id text not null,
  storage_path text not null,
  width integer,
  height integer,
  byte_size integer,

  terms_accepted_at timestamptz,
  terms_version text,

  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  rejection_reason text,

  -- Que card creo al aprobarse. Es la trazabilidad de vuelta: de una card del
  -- catalogo se puede llegar a quien la propuso y con que datos.
  created_card_id integer references public.cards(id) on delete set null,

  created_at timestamptz not null default now()
);

comment on table public.card_submissions is
  'Propuestas de cards que no estan en el catalogo. Al aprobarse crean una fila '
  'en cards y otra en card_images; ver created_card_id.';

-- ---------------------------------------------------------------------------
-- 2. Constraints: el estado no puede quedar a medias
-- ---------------------------------------------------------------------------

-- Los 8 valores que cards.member usa hoy. cards.member es texto libre, pero la
-- app mapea el nombre a un MemberInfo para sacar colores y emoji: un valor
-- fuera de la lista se veria sin color y sin inicial. Mejor rechazarlo aca que
-- descubrirlo en la grilla.
alter table public.card_submissions
  drop constraint if exists card_submissions_member_known;
alter table public.card_submissions
  add constraint card_submissions_member_known check (
    member in ('RM', 'Jin', 'Suga', 'J-Hope', 'Jimin', 'V', 'Jungkook', 'Group')
  );

alter table public.card_submissions
  drop constraint if exists card_submissions_card_name_len;
alter table public.card_submissions
  add constraint card_submissions_card_name_len check (
    length(btrim(card_name)) between 2 and 120
  );

alter table public.card_submissions
  drop constraint if exists card_submissions_notes_len;
alter table public.card_submissions
  add constraint card_submissions_notes_len check (
    notes is null or length(notes) <= 500
  );

-- Mientras esta pendiente, la imagen vive en el bucket PRIVADO. Es la misma
-- garantia que da card_images: nada sin revisar es accesible publicamente, y no
-- depende de que el cliente se porte bien.
alter table public.card_submissions
  drop constraint if exists card_submissions_pending_is_private;
alter table public.card_submissions
  add constraint card_submissions_pending_is_private check (
    status <> 'pending' or bucket_id = 'photocard-community-review'
  );

-- Sin constancia de los terminos no hay aporte. Misma regla que
-- card_images_community_has_terms.
alter table public.card_submissions
  drop constraint if exists card_submissions_has_terms;
alter table public.card_submissions
  add constraint card_submissions_has_terms check (
    terms_accepted_at is not null and terms_version is not null
  );

alter table public.card_submissions
  drop constraint if exists card_submissions_resolved_has_reviewer;
alter table public.card_submissions
  add constraint card_submissions_resolved_has_reviewer check (
    status = 'pending' or (reviewed_by is not null and reviewed_at is not null)
  );

alter table public.card_submissions
  drop constraint if exists card_submissions_rejected_has_reason;
alter table public.card_submissions
  add constraint card_submissions_rejected_has_reason check (
    status <> 'rejected' or rejection_reason is not null
  );

-- Una propuesta aprobada sin card creada seria una mentira: la bandeja diria
-- "aprobada" y el catalogo no tendria nada.
alter table public.card_submissions
  drop constraint if exists card_submissions_approved_has_card;
alter table public.card_submissions
  add constraint card_submissions_approved_has_card check (
    status <> 'approved' or created_card_id is not null
  );

-- ---------------------------------------------------------------------------
-- 3. Indices
-- ---------------------------------------------------------------------------

-- La bandeja de moderacion: pendientes, mas viejas primero.
create index if not exists card_submissions_pending_idx
  on public.card_submissions (created_at)
  where status = 'pending';

-- "mis propuestas" en el perfil.
create index if not exists card_submissions_submitted_by_idx
  on public.card_submissions (submitted_by);

-- Doble envio de lo mismo. No impide que dos personas propongan la misma card
-- --eso lo resuelve la moderacion, que ahi si hace falta criterio-- pero si que
-- una misma persona mande dos veces la misma mientras la primera espera.
create unique index if not exists card_submissions_no_dup_pending
  on public.card_submissions (submitted_by, album_id, category_id, member, lower(btrim(card_name)))
  where status = 'pending';

-- ---------------------------------------------------------------------------
-- 4. Coherencia de la taxonomia (trigger)
-- ---------------------------------------------------------------------------

-- SECURITY DEFINER porque lee albums/album_versions/card_sets y tiene que
-- funcionar igual para quien sea; search_path vacio y EXECUTE revocado a PUBLIC
-- (leccion de SR-9: hay que quitarselo a public, no a anon).
create or replace function public.card_submissions_derive_taxonomy()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_era_id bigint;
  v_type_id bigint;
begin
  -- Tipo y era salen del album, no del cliente.
  select a.era_id, e.collection_type_id
    into v_era_id, v_type_id
  from public.albums a
    left join public.album_eras e on e.id = a.era_id
  where a.id = new.album_id;

  new.era_id := v_era_id;
  new.collection_type_id := v_type_id;

  -- Una version de OTRO album, o un set de otro album, describirian una card
  -- que no puede existir. Se rechaza en vez de guardarse para que el moderador
  -- lo descubra.
  if new.version_id is not null and not exists (
    select 1 from public.album_versions v
    where v.id = new.version_id and v.album_id = new.album_id
  ) then
    raise exception 'version_id % no pertenece al album %', new.version_id, new.album_id;
  end if;

  if new.card_set_id is not null and not exists (
    select 1 from public.card_sets s
    where s.id = new.card_set_id and s.album_id = new.album_id
  ) then
    raise exception 'card_set_id % no pertenece al album %', new.card_set_id, new.album_id;
  end if;

  -- El handle se copia igual que en card_images: la RLS de user_profiles no deja
  -- que la bandeja lea el perfil de otra persona, asi que viaja con la fila.
  if new.submitted_by is null then
    new.contributor_handle := null;
  else
    select p.username into new.contributor_handle
    from public.user_profiles p
    where p.id = new.submitted_by;
  end if;

  return new;
end;
$$;

drop trigger if exists card_submissions_derive_taxonomy_trg on public.card_submissions;
create trigger card_submissions_derive_taxonomy_trg
  before insert or update of album_id, version_id, card_set_id, submitted_by
  on public.card_submissions
  for each row execute function public.card_submissions_derive_taxonomy();

revoke execute on function public.card_submissions_derive_taxonomy() from public;

-- Si alguien cambia su handle, tambien cambia en sus propuestas. El de
-- card_images ya hacia esto; aca se extiende en la misma funcion para que no
-- queden dos sitios que puedan divergir.
create or replace function public.user_profiles_sync_handle()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.username is distinct from old.username then
    update public.card_images
    set contributor_handle = new.username
    where contributed_by = new.id;

    update public.card_submissions
    set contributor_handle = new.username
    where submitted_by = new.id;
  end if;
  return new;
end;
$$;

revoke execute on function public.user_profiles_sync_handle() from public;

-- ---------------------------------------------------------------------------
-- 5. RLS
-- ---------------------------------------------------------------------------

alter table public.card_submissions enable row level security;

-- Cada quien ve solo las suyas. No hay lectura publica, a diferencia de
-- card_images: una propuesta aprobada ya esta en el catalogo como card, asi que
-- exponer la fila no aportaria nada y si expondria el texto de `notes`.
drop policy if exists "card_submissions submitter reads own" on public.card_submissions;
create policy "card_submissions submitter reads own"
  on public.card_submissions for select to authenticated
  using (submitted_by = auth.uid());

-- Nada sensible lo decide el cliente: el estado nace pendiente, la imagen en el
-- bucket privado, la autoria es la propia, y los campos de revision y la card
-- creada tienen que venir vacios. Un cliente modificado no puede autoaprobarse
-- una card ni proponerla en nombre de otra persona.
drop policy if exists "card_submissions submitter creates own" on public.card_submissions;
create policy "card_submissions submitter creates own"
  on public.card_submissions for insert to authenticated
  with check (
    submitted_by = auth.uid()
    and status = 'pending'
    and bucket_id = 'photocard-community-review'
    and terms_accepted_at is not null
    and terms_version is not null
    and reviewed_by is null
    and reviewed_at is null
    and rejection_reason is null
    and created_card_id is null
  );

-- Para poder retirar una propuesta antes de que la revisen, y para que
-- submitContribution() pueda limpiar si la subida quedo a medias.
drop policy if exists "card_submissions submitter deletes own pending" on public.card_submissions;
create policy "card_submissions submitter deletes own pending"
  on public.card_submissions for delete to authenticated
  using (submitted_by = auth.uid() and status = 'pending');

drop policy if exists "card_submissions admin all" on public.card_submissions;
create policy "card_submissions admin all"
  on public.card_submissions for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- 6. Grants
-- ---------------------------------------------------------------------------

-- Supabase tiene `alter default privileges` concediendo todo a anon en las
-- tablas nuevas: una tabla recien creada NO nace cerrada. Es el mismo error que
-- el comentario de create_image_reports afirmaba al reves.
revoke all on public.card_submissions from anon;

-- Sin UPDATE, ni para authenticated ni para el admin. Resolver una propuesta
-- significa crear una card y mover un objeto entre buckets, y eso solo lo hace
-- la edge function moderate-card-submission con service_role. Que un admin no
-- pueda hacerlo por PostgREST evita dejar una propuesta aprobada sin card, o una
-- card sin imagen.
revoke update on public.card_submissions from authenticated;
grant select, insert, delete on public.card_submissions to authenticated;
